packages = {

	'kali-linux-large' : ['kali-linux-core', 'kali-linux-default', '0trace', 'ace-voip', 'afflib-tools', 'amap', 'apache-users', 'apktool', 'armitage', 'arpwatch', 'asleap', 'automater', 'backdoor-factory', 'bbqsql', 'bdfproxy', 'bed', 'beef-xss', 'blindelephant', 'bluelog', 'blueranger', 'bluesnarfer', 'braa', 'btscanner', 'cabextract', 'cdpsnarf', 'chirp', 'cisco-auditing-tool', 'cisco-global-exploiter', 'cisco-ocs', 'cisco-torch', 'cmospwd', 'copy-router-config', 'cowpatty', 'cymothoa', 'darkstat', 'dc3dd', 'dcfldd', 'ddrescue', 'deblaze', 'dex2jar', 'dhcpig', 'dnmap', 'dnsmap', 'dnstracer', 'dnswalk', 'doona', 'dotdotpwn', 'dradis', 'driftnet', 'dsniff', 'dumpzilla', 'eapmd5pass', 'enumiax', 'ettercap-graphical', 'ewf-tools', 'extundelete', 'fcrackzip', 'ferret-sidejack', 'fiked', 'fimap', 'flasm', 'foremost', 'fragroute', 'fragrouter', 'framework2', 'ftester', 'funkload', 'galleta', 'golismero', 'grabber', 'hackrf', 'hamster-sidejack', 'hexinject', 'httrack', 'iaxflood', 'intersect', 'intrace', 'inviteflood', 'irpas', 'jad', 'javasnoop', 'jboss-autopwn', 'johnny', 'joomscan', 'jsql-injection', 'keimpx', 'killerbee', 'kismet-logtools', 'libfindrtp', 'libfreefare-bin', 'libhivex-bin', 'libnfc-bin', 'lynis', 'mdbtools', 'mdk3', 'medusa', 'memdump', 'mercurial', 'mfcuk', 'mfoc', 'mfterm', 'missidentify', 'ncat-w32', 'netwag', 'nipper-ng', 'nishang', 'ohrwurm', 'ollydbg', 'oscanner', 'p0f', 'pack', 'padbuster', 'paros', 'pasco', 'pdgmail', 'perl-cisco-copyconfig', 'pev', 'plecost', 'polenum', 'powerfuzzer', 'protos-sip', 'proxystrike', 'pst-utils', 'pyrit', 'python-rfidiot', 'rainbowcrack', 'rcracki-mt', 'recoverjpeg', 'recstudio', 'redfang', 'reglookup', 'regripper', 'rifiuti', 'rifiuti2', 'rtpbreak', 'rtpflood', 'rtpinsertsound', 'rtpmixsound', 'safecopy', 'sctpscan', 'sfuzz', 'sidguesser', 'siege', 'siparmyknife', 'sipcrack', 'sipp', 'sipvicious', 'smali', 'smtp-user-enum', 'sniffjoke', 'spectools', 'sqldict', 'sqlninja', 'sqlsus', 'sslsniff', 'subversion', 'sucrack', 't50', 'termineter', 'tftpd32', 'thc-ssl-dos', 'tlssled', 'tnscmd10g', 'truecrack', 'twofi', 'u3-pwn', 'ua-tester', 'unicornscan', 'uniscan', 'urlcrazy', 'vinetto', 'volafox', 'volatility', 'wapiti', 'wce', 'webacoo', 'webscarab', 'wifi-honey', 'wifitap', 'wol-e', 'xprobe', 'xspy', 'xsser', 'yersinia', 'zaproxy', 'zim', 'cgpt', 'chkrootkit', 'edb-debugger', 'gdb', 'mc', 'tcpflow', 'vim-gtk', 'zerofree'],

	'kali-linux-web': ['apache-users', 'apache2', 'arachni', 'automater', 'bbqsql', 'beef-xss', 'blindelephant', 'burpsuite', 'cadaver', 'clusterd', 'commix', 'cookie-cadger', 'cutycapt', 'davtest', 'deblaze', 'default-mysql-server', 'dirb', 'dirbuster', 'dnmap', 'dotdotpwn', 'eyewitness', 'ferret-sidejack', 'fimap', 'ftester', 'funkload', 'golismero', 'grabber', 'hamster-sidejack', 'heartleech', 'hexorbase', 'httprint', 'httrack', 'hydra', 'hydra-gtk', 'jboss-autopwn', 'joomscan', 'jsql-injection', 'laudanum', 'lbd', 'maltego', 'maltego-teeth', 'medusa', 'mitmproxy', 'ncrack', 'nikto', 'nishang', 'nmap', 'oscanner', 'owasp-mantra-ff', 'padbuster', 'paros', 'patator', 'php', 'php-mysql', 'plecost', 'powerfuzzer', 'proxychains', 'proxystrike', 'proxytunnel', 'python-halberd', 'redsocks', 'sidguesser', 'siege', 'skipfish', 'slowhttptest', 'sqldict', 'sqlitebrowser', 'sqlmap', 'sqlninja', 'sqlsus', 'sslcaudit', 'ssldump', 'sslh', 'sslscan', 'sslsniff', 'sslsplit', 'sslstrip', 'sslyze', 'stunnel4', 'thc-ssl-dos', 'tlssled', 'tnscmd10g', 'ua-tester', 'uniscan', 'wafw00f', 'wapiti', 'watobo', 'webacoo', 'webhandler', 'webscarab', 'webshells', 'weevely', 'wfuzz', 'whatweb', 'wireshark', 'wpscan', 'xsser', 'zaproxy'],

	'kali-linux-database' : ['bbqsql', 'hexorbase', 'jsql-injection', 'mdbtools', 'oscanner', 'sidguesser', 'sqldict', 'sqlitebrowser', 'sqlmap', 'sqlninja', 'sqlsus', 'tnscmd10g'],

	'kali-linux-passwords': ['kali-tools-gpu', 'cewl', 'chntpw', 'cisco-auditing-tool', 'cmospwd', 'crackle', 'creddump', 'crunch', 'fcrackzip', 'findmyhash', 'freerdp2-x11', 'gpp-decrypt', 'hash-identifier', 'hashcat', 'hashcat-utils', 'hashid', 'hydra', 'hydra-gtk', 'john', 'johnny', 'keimpx', 'maskprocessor', 'medusa', 'mimikatz', 'ncrack', 'oclhashcat', 'onesixtyone', 'ophcrack', 'ophcrack-cli', 'pack', 'passing-the-hash', 'patator', 'pdfcrack', 'pipal', 'polenum', 'pyrit', 'rainbowcrack', 'rarcrack', 'rcracki-mt', 'rsmangler', 'samdump2', 'seclists', 'sipcrack', 'sipvicious', 'smbmap', 'sqldict', 'statsprocessor', 'sucrack', 'thc-pptp-bruter', 'truecrack', 'twofi', 'wce', 'wordlists'],

	'kali-linux-wireless': ['kali-tools-802-11', 'kali-tools-bluetooth', 'kali-tools-rfid', 'kali-tools-sdr', 'killerbee', 'rfcat', 'rfkill', 'sakis3g', 'spectools', 'wireshark'],

	'kali-linux-vulnerability': ['ace', 'afl', 'bed', 'cisco-auditing-tool', 'cisco-global-exploiter', 'cisco-ocs', 'cisco-torch', 'copy-router-config', 'dhcpig', 'enumiax', 'golismero', 'iaxflood', 'inviteflood', 'lynis', 'nikto', 'nmap', 'ohrwurm', 'openvas', 'powerfuzzer', 'protos-sip', 'rtpbreak', 'rtpflood', 'rtpinsertsound', 'rtpmixsound', 'sctpscan', 'sfuzz', 'siege', 'siparmyknife','sipp', 'sipsak', 'sipvicious', 'slowhttptest', 'sparta', 'spike', 't50', 'thc-ssl-dos', 'unix-privesc-check', 'voiphopper', 'yersinia'],

	'kali-linux-information-gathering': ['0trace', 'arping', 'automater', 'braa', 'cdpsnarf', 'dmitry', 'dnmap', 'dnsenum', 'dnsmap', 'dnsrecon', 'dnstracer', 'dnswalk', 'enum4linux', 'fierce', 'firewalk', 'fping', 'fragroute', 'fragrouter', 'ftester', 'hping3', 'ike-scan', 'intrace', 'irpas', 'lbd', 'maltego', 'masscan', 'metagoofil', 'miranda', 'nbtscan', 'ncat', 'netdiscover', 'netmask', 'nmap', 'onesixtyone', 'p0f', 'recon-ng', 'smbmap', 'smtp-user-enum', 'snmpcheck', 'sparta', 'sslcaudit', 'ssldump', 'sslh', 'sslscan', 'sslyze', 'swaks', 'thc-ipv6', 'theharvester', 'tlssled', 'twofi', 'unicornscan', 'urlcrazy', 'wafw00f', 'wol-e', 'xprobe', 'zenm'],

	'kali-linux-light': ['kali-linux-core', 'firefox-esr', 'openssh-server'],

	'kali-linux-core': ['cifs-utils', 'ftp', 'gdisk', 'iw', 'lvm2', 'mlocate', 'netcat-traditional', 'nfs-common', 'openssh-server', 'openvpn', 'p7zip-full', 'parted', 'rfkill', 'samba', 'snmp', 'sudo', 'tcpdump', 'testdisk', 'tftp', 'tightvncserver','tmux', 'unrar', 'vim', 'whois'],

	'kali-linux-default': ['kali-linux-core', 'aircrack-ng', 'amass', 'arp-scan', 'arping', 'autopsy', 'binwalk', 'bluez', 'bluez-hcidump', 'bulk-extractor', 'bully', 'burpsuite', 'cadaver', 'cewl', 'cherrytree', 'chntpw', 'clusterd', 'commix', 'creddump', 'crunch', 'cryptcat', 'cutycapt', 'davtest', 'dbd', 'dirb', 'dirbuster', 'dmitry', 'dns2tcp', 'dnschef', 'dnsenum', 'dnsrecon', 'enum4linux', 'exe2hexbat', 'exiv2', 'exploitdb', 'fern-wifi-cracker', 'fierce', 'findmyhash', 'fping', 'ghost-phisher', 'gpp-decrypt', 'guymager', 'hash-identifier', 'hashcat', 'hashcat-utils', 'hashid', 'hexorbase', 'hping3', 'hydra', 'hydra-gtk', 'i2c-tools', 'ike-scan', 'impacket-scripts', 'inetsim', 'iodine', 'john','king-phisher', 'kismet', 'laudanum', 'lbd', 'macchanger', 'magicrescue', 'maltego', 'maltego-teeth', 'maskprocessor', 'masscan', 'metasploit-framework', 'mimikatz', 'miranda', 'mitmproxy', 'msfpc', 'nasm', 'nbtscan', 'ncrack', 'ncurses-hexedit', 'netdiscover', 'netsed', 'nfspy', 'nikto', 'nmap', 'onesixtyone', 'ophcrack', 'ophcrack-cli', 'passing-the-hash', 'patator', 'pdf-parser', 'pdfid', 'pipal', 'pixiewps', 'powersploit', 'proxychains', 'proxytunnel', 'ptunnel', 'python-faraday', 'python-impacket', 'python-peepdf', 'python-scapy', 'radare2', 'reaver', 'rebind', 'recon-ng', 'redsocks', 'responder', 'rsmangler', 'samdump2', 'sbd', 'scalpel', 'scrounge-ntfs', 'set', 'skipfish', 'sleuthkit', 'smbmap', 'snmpcheck', 'sparta', 'spike', 'spooftooph', 'sqlmap', 'sslcaudit', 'ssldump', 'sslscan', 'sslsplit', 'sslstrip', 'sslyze', 'statsprocessor', 'thc-ipv6', 'thc-pptp-bruter', 'theharvester', 'udptunnel', 'unix-privesc-check', 'voiphopper', 'wafw00f', 'webshells', 'weevely', 'wfuzz', 'whatweb', 'wifite', 'windows-binaries', 'winexe', 'wireshark', 'wordlists', 'wpscan', 'zenmap', 'apache2', 'atftpd', 'axel', 'clang', 'cryptsetup', 'cryptsetup-nuke-password', 'curlftpfs', 'default-mysql-server', 'dos2unix', 'ethtool', 'expect', 'gparted', 'git', 'hashdeep', 'hotpatch', 'ifenslave', 'minicom', 'miredo', 'multimac', 'netmask', 'netsniff-ng', 'ngrep', 'php', 'php-mysql', 'pwnat', 'rake', 'rdesktop', 'recordmydesktop', 'sakis3g', 'screen', 'sendemail', 'snmpd', 'socat', 'sqlitebrowser', 'sslh', 'stunnel4', 'swaks', 'tcpick', 'tcpreplay', 'upx-ucl', 'vboot-kernel-utils', 'vboot-utils', 'vlan', 'vpnc', 'xpdf', 'xtightvncviewer'],

	'kali-linux-reverse-engineering': ['apktool', 'clang', 'dex2jar', 'edb-debugger', 'flasm', 'jad', 'javasnoop', 'jd-gui', 'metasploit-framework', 'ollydbg', 'radare2', 'radare2-cutter', 'recstudio'],

	'kali-linux-exploitation': ['armitage', 'beef-xss', 'exploitdb', 'metasploit-framework', 'msfpc', 'sandi', 'set', 'shellnoob', 'sqlmap', 'termineter', 'vfeed'],

	'kali-linux-social-engineering': ['backdoor-factory', 'beef-xss', 'ghost-phisher', 'maltego', 'msfpc', 'set', 'u3-pwn', 'veil'],

	'kali-linx-sniffing-spoofing': ['bdfproxy', 'bettercap', 'darkstat', 'dnschef', 'driftnet', 'dsniff', 'ettercap-graphical', 'ferret-sidejack', 'fiked', 'hamster-sidejack', 'hexinject', 'isr-evilgrade', 'macchanger', 'mitmproxy', 'netsniff-ng', 'nfspy', 'rebind', 'responder', 'sniffjoke', 'sslsniff', 'sslsplit', 'sslstrip', 'tcpflow', 'tcpreplay', 'wifi-honey', 'wireshark', 'yersinia'],

	'kali-linux-post-exploitation': ['backdoor-factory', 'bdfproxy', 'cymothoa', 'dbd', 'dns2tcp', 'exe2hexbat', 'intersect', 'iodine', 'laudanum', 'mimikatz', 'miredo', 'nishang', 'powersploit', 'proxychains', 'proxytunnel', 'ptunnel', 'pwnat', 'sbd', 'shellter', 'sslh', 'stunnel4', 'u3-pwn', 'udptunnel', 'veil', 'webacoo', 'weevely'],

	'kali-linux-forensics': ['afflib-tools', 'apktool', 'autopsy', 'binwalk', 'bulk-extractor', 'cabextract', 'chkrootkit', 'creddump', 'dc3dd', 'dcfldd', 'ddrescue', 'dumpzilla', 'edb-debugger', 'ewf-tools', 'exiv2', 'extundelete', 'fcrackzip', 'firmware-mod-kit', 'flasm', 'foremost', 'galleta', 'gdb', 'gparted', 'guymager', 'hashdeep', 'inetsim', 'jad', 'javasnoop', 'libhivex-bin', 'lvm2', 'lynis', 'magicrescue', 'mdbtools', 'memdump', 'missidentify', 'nasm', 'ollydbg', 'p7zip-full', 'parted', 'pasco', 'pdf-parser', 'pdfid', 'pdgmail', 'pev', 'polenum', 'pst-utils', 'python-capstone', 'python-distorm3', 'python-peepdf', 'radare2', 'radare2-cutter', 'recoverjpeg', 'recstudio', 'reglookup', 'regripper', 'rifiuti', 'rifiuti2', 'rkhunter', 'safecopy', 'samdump2', 'scalpel', 'scrounge-ntfs', 'sleuthkit', 'smali', 'sqlitebrowser', 'ssdeep', 'tcpdump', 'tcpflow', 'tcpick', 'tcpreplay', 'truecrack', 'unrar', 'upx-ucl', 'vinetto', 'volafox', 'volatility', 'wce', 'wireshark', 'xplico', 'yara', 'libaff4-utils', 'exifprobe', 'ext3grep', 'ext4magic', 'forensic-artifacts', 'forensics-colorize', 'gpart', 'grokevt', 'lime-forensics', 'mac-robber', 'md5deep', 'metacam', 'myrescue', 'nasty', 'neopi', 'plaso', 'python-binplist', 'python-dfdatetime', 'python-dfvfs', 'python-dfwinreg', 'recoverdm', 'rekall-core', 'rephrase', 'rsakeyfind', 'ssdeep', 'undbx', 'unhide', 'winregfs', 'xmount'],

	'kali-linux-reporting': ['cutycapt', 'dradis', 'eyewitness', 'maltego', 'metagoofil', 'pipal', 'python-faraday', 'recordmydesktop'],

	'kali-linux-gpu': ['oclgausscrack', 'oclhashcat', 'pyrit', 'truecrack'],

	'kali-linux-crypto-stego': ['aesfix', 'aeskeyfind', 'ccrypt', 'outguess', 'steghide', 'stegsnow'],

	'kali-linux-hardware': ['binwalk', 'cutecom', 'flashrom', 'minicom', 'openocd', 'qemu', 'radare2', 'radare2-cutter'],

	'kali-linux-fuzzing': ['afl', 'sandsifter', 'sfuzz', 'spike', 'wfuzz', ],

	'kali-linux-802.11': ['aircrack-ng', 'asleap', 'bully', 'cowpatty', 'eapmd5pass', 'fern-wifi-cracker', 'freeradius-wpe', 'ghost-phisher', 'iw', 'kismet', 'macchanger', 'mdk3', 'mdk4', 'oclhashcat', 'pixiewps', 'pyrit', 'reaver', 'wifi-honey', 'wifitap', 'wifite'],

	'kali-linux-bluetooth': ['bluelog', 'blueranger', 'bluesnarfer', 'bluez', 'bluez-hcidump', 'btscanner', 'crackle', 'redfang'],

	'kali-linux-rfid': ['gnuradio', 'libfreefare-bin', 'libnfc-bin', 'mfcuk', 'mfoc', 'mfterm', 'python-rfidiot', 'rfdump', ],

	'kali-linux-sdr': ['chirp', 'gnuradio', 'gqrx', 'gqrx-sdr', 'gr-air-modes', 'gr-iqbal', 'gr-osmosdr', 'hackrf', 'inspectrum', 'kalibrate-rtl', 'libgnuradio-baz', 'multimon-ng', 'rtlsdr-scanner', 'uhd-host', 'uhd-images'],

	'kali-linux-voip': ['ace-voip', 'dnmap', 'enumiax', 'iaxflood', 'inviteflood', 'libfindrtp', 'nmap', 'ohrwurm', 'protos-sip', 'rtpbreak', 'rtpflood', 'rtpinsertsound', 'rtpmixsound', 'sctpscan', 'siparmyknife', 'sipcrack', 'sipp', 'sipvicious', 'voiphopper', 'wireshark'],

	'kali-linux-windows-tools': ['dbd', 'dnschef', 'heartleech', 'hyperion', 'mimikatz', 'ncat-w32', 'ollydbg', 'powercat', 'regripper', 'sbd', 'secure-socket-funneling-windows-binaries', 'shellter', 'tftpd32', 'wce', 'windows-binaries', 'windows-privesc-check'],

	'kali-linux-top10': ['aircrack-ng', 'burpsuite', 'crackmapexec', 'hydra', 'john', 'metasploit-framework', 'nmap', 'responder', 'sqlmap', 'wireshark'],

	'kali-linux-everything': ['kali-linux-core', 'kali-linux-default', 'kali-linux-large', 'kali-linux-nethunter', 'kali-linux-802-11', 'kali-linux-bluetooth', 'kali-linux-database', 'kali-linux-exploitation', 'kali-linux-forensics', 'kali-linux-fuzzing', 'kali-linux-gpu', 'kali-linux-hardware', 'kali-linux-headless', 'kali-linux-information-gathering', 'kali-linux-passwords', 'kali-linux-post-exploitation', 'kali-linux-reporting', 'kali-linux-reverse-engineering', 'kali-linux-rfid', 'kali-linux-sdr', 'kali-linux-sniffing-spoofing', 'kali-linux-social-engineering', 'kali-linux-crypto-stego', 'kali-linux-top10', 'kali-linux-voip', 'kali-linux-vulnerability', 'kali-linux-web', 'kali-linux-windows-resources', 'kali-linux-wireless', 'android-sdk', 'device-pharmer', 'exploitdb-bin-sploits', 'exploitdb-papers', 'freeradius', 'hackersh', 'htshells', 'ident-user-enum', 'ismtp', 'linux-exploit-suggester', 'openvas', 'parsero', 'payloadsallthethings', 'python-halberd', 'sandi', 'set', 'shellnoob', 'shellter', 'teamsploit', 'veil', 'webhandler', 'websploit', 'bruteforce-salted-openssl', 'brutespray', 'capstone-tool', 'changeme', 'chaosreader', 'crack', 'dislocker', 'goldeneye', 'knocker', 'nmapsi4', 'o-saft', 'pnscan', 'pompem', 'princeprocessor', 'shed', 'testssl.sh', 'wig'],

	'offsec-awae': ['kali-linux-core', 'burpsuite', 'firefox-esr', 'impacket-scripts', 'netcat-traditional', 'network-manager-openvpn-gnome', 'openjdk-11-jdk-headless', 'python2', 'rdesktop', 'xfreerdp'],

	'offsec-pwk': ['kali-linux-core', 'apache2', 'atftpd', 'cewl', 'cherrytree', 'crunch', 'dnsenum', 'dnsrecon', 'dnsutils', 'edb-debugger', 'enum4linux', 'exploitdb', 'firefox-esr', 'hash-identifier', 'hydra', 'iptables', 'john', 'medusa', 'metasploit-framework', 'mingw-w64', 'nano', 'nbtscan', 'ncat', 'ncrack', 'net-tools', 'netcat-traditional', 'network-manager-openvpn-gnome', 'nmap', 'onesixtyone', 'openjdk-11-jdk-headless', 'openssh-server', 'openvas', 'openvpn', 'passing-the-hash', 'proxychains', 'pure-ftpd', 'python', 'recon-ng', 'rinetd', 'sbd', 'snmp', 'snmpcheck', 'sqlmap', 'stunnel4', 'tcpdump', 'theharvester', 'upx-ucl', 'wget', 'whois', 'windows-binaries', 'wine', 'wireshark']

}
